package com.newsoft.users.controller;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.newsoft.users.exceptions.ResourceNotFoundException;
import com.newsoft.users.model.User;
import com.newsoft.users.model.UserRequest;
import com.newsoft.users.model.UserResponse;
import com.newsoft.users.repository.UserRepository;
import com.newsoft.users.serviceImpl.UserServiceImpl;
import com.newsoft.users.utils.JwtUtil;

@CrossOrigin(origins = "http://localhost:4200")
@RestController
@RequestMapping("/api/v1/")
public class UserController {

	@Autowired
	private UserRepository userRepository;

	@Autowired
	private AuthenticationManager authenticationManager;

	@Autowired
	private JwtUtil jwtUtil;
	@Autowired
	private UserServiceImpl userServiceImpl;

	// get all users
	@GetMapping("/users")
	public List<User> getUsers() {
		return userRepository.findAll();
	}

	// create users rest api

	@PostMapping("/users")
	public ResponseEntity<String> createUser(@Valid @RequestBody User user) {
		Integer id = userServiceImpl.saveUser(user);
		return ResponseEntity.ok("User saved with id " + id);

	}

	// get user by id rest api
	@GetMapping("/users/{id}")
	public ResponseEntity<User> getUserById(@PathVariable Integer id) {
		User user = userRepository.findById(id)
				.orElseThrow(() -> new ResourceNotFoundException("User not exist with id :" + id));
		return ResponseEntity.ok(user);
	}

	// update user rest api

	@PutMapping("/users/{id}")
	public ResponseEntity<User> updateUser(@PathVariable Integer id, @RequestBody User userDetails) {
		User user = userRepository.findById(id)
				.orElseThrow(() -> new ResourceNotFoundException("User not exist with id :" + id));

		user.setFirstName(userDetails.getFirstName());
		user.setLastName(userDetails.getLastName());
		user.setEmailId(userDetails.getEmailId());

		User updatedUser = userRepository.save(user);
		return ResponseEntity.ok(updatedUser);
	}

	// delete user rest api
	@DeleteMapping("/users/{id}")
	public ResponseEntity<Map<String, Boolean>> deleteUser(@PathVariable Integer id) {
		User user = userRepository.findById(id)
				.orElseThrow(() -> new ResourceNotFoundException("User not exist with id :" + id));

		userRepository.delete(user);
		Map<String, Boolean> response = new HashMap<>();
		response.put("deleted", Boolean.TRUE);
		return ResponseEntity.ok(response);
	}

//search data by first name or sur name or pincode
	@GetMapping("/userName")
	public List<User> getUserByFirstNameOrSurnameAndPincode(@RequestParam(required = false) String firstName,
			@RequestParam(required = false) String lastName, @RequestParam(required = false) Integer pinCode) {
		return userRepository.findByFirstNameOrLastNameOrPinCode(firstName, lastName, pinCode);
	}

//search by join date
	@GetMapping("/userjoindate")
	public List<User> getUserByJoinDate() {
		return userRepository.findByOrderByJoinDateAsc();
	}

//login api
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest) {
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(userRequest.getUsername(), userRequest.getPassword()));
		System.out.println("INSIDE LOGIN USER");
		String token = jwtUtil.generateToken(userRequest.getUsername());
		System.out.println("The Generated Token is :" + token);
		return ResponseEntity.ok(new UserResponse(token, "GENERATED BY MR.DEVENDRA -NeoSoft"));
	}
}
